CREATE TABLE [A](
  [id-a] INTEGER PRIMARY KEY AUTOINCREMENT,
  [mot] VARCHAR NOT NULL,
  [type] VARCHAR NOT NULL);
  
  
  CREATE TABLE [B](
  [id-b] INTEGER PRIMARY KEY AUTOINCREMENT,
  [mot] VARCHAR NOT NULL,
  [type] VARCHAR NOT NULL);
  
  
  CREATE TABLE [C](
  [id-c] INTEGER PRIMARY KEY AUTOINCREMENT,
  [mot] VARCHAR NOT NULL,
  [type] VARCHAR NOT NULL);
  
  
  CREATE TABLE [D](
  [id-d] INTEGER PRIMARY KEY AUTOINCREMENT,
  [mot] VARCHAR NOT NULL,
  [type] VARCHAR NOT NULL);
  
  
  CREATE TABLE [E](
  [id-e] INTEGER PRIMARY KEY AUTOINCREMENT,
  [mot] VARCHAR NOT NULL,
  [type] VARCHAR NOT NULL);
  
  
  CREATE TABLE [F](
  [id-f] INTEGER PRIMARY KEY AUTOINCREMENT,
  [mot] VARCHAR NOT NULL,
  [type] VARCHAR NOT NULL);
  
    CREATE TABLE [H](
  [id-h] INTEGER PRIMARY KEY AUTOINCREMENT,
  [mot] VARCHAR NOT NULL,
  [type] VARCHAR NOT NULL);
  
      CREATE TABLE [I](
  [id-i] INTEGER PRIMARY KEY AUTOINCREMENT,
  [mot] VARCHAR NOT NULL,
  [type] VARCHAR NOT NULL);
  
  
        CREATE TABLE [J](
  [id-j] INTEGER PRIMARY KEY AUTOINCREMENT,
  [mot] VARCHAR NOT NULL,
  [type] VARCHAR NOT NULL);
  
          CREATE TABLE [K](
  [id-k] INTEGER PRIMARY KEY AUTOINCREMENT,
  [mot] VARCHAR NOT NULL,
  [type] VARCHAR NOT NULL);
  
            CREATE TABLE [L](
  [id-l] INTEGER PRIMARY KEY AUTOINCREMENT,
  [mot] VARCHAR NOT NULL,
  [type] VARCHAR NOT NULL);
  
            CREATE TABLE [M](
  [id-m] INTEGER PRIMARY KEY AUTOINCREMENT,
  [mot] VARCHAR NOT NULL,
  [type] VARCHAR NOT NULL);
  
            CREATE TABLE [N](
  [id-n] INTEGER PRIMARY KEY AUTOINCREMENT,
  [mot] VARCHAR NOT NULL,
  [type] VARCHAR NOT NULL);
  
            CREATE TABLE [O](
  [id-o] INTEGER PRIMARY KEY AUTOINCREMENT,
  [mot] VARCHAR NOT NULL,
  [type] VARCHAR NOT NULL);
  
            CREATE TABLE [P](
  [id-p] INTEGER PRIMARY KEY AUTOINCREMENT,
  [mot] VARCHAR NOT NULL,
  [type] VARCHAR NOT NULL);
  
  
            CREATE TABLE [Q](
  [id-q] INTEGER PRIMARY KEY AUTOINCREMENT,
  [mot] VARCHAR NOT NULL,
  [type] VARCHAR NOT NULL);
  
  
            CREATE TABLE [R](
  [id-r] INTEGER PRIMARY KEY AUTOINCREMENT,
  [mot] VARCHAR NOT NULL,
  [type] VARCHAR NOT NULL);


          CREATE TABLE [S](
  [id-s] INTEGER PRIMARY KEY AUTOINCREMENT,
  [mot] VARCHAR NOT NULL,
  [type] VARCHAR NOT NULL);
  
  
  
            CREATE TABLE [T](
  [id-t] INTEGER PRIMARY KEY AUTOINCREMENT,
  [mot] VARCHAR NOT NULL,
  [type] VARCHAR NOT NULL);
  
  
            CREATE TABLE [U](
  [id-u] INTEGER PRIMARY KEY AUTOINCREMENT,
  [mot] VARCHAR NOT NULL,
  [type] VARCHAR NOT NULL);
  
            CREATE TABLE [V](
  [id-v] INTEGER PRIMARY KEY AUTOINCREMENT,
  [mot] VARCHAR NOT NULL,
  [type] VARCHAR NOT NULL);
  
  
            CREATE TABLE [W](
  [id-w] INTEGER PRIMARY KEY AUTOINCREMENT,
  [mot] VARCHAR NOT NULL,
  [type] VARCHAR NOT NULL);
  
  
            CREATE TABLE [Y](
  [id-y] INTEGER PRIMARY KEY AUTOINCREMENT,
  [mot] VARCHAR NOT NULL,
  [type] VARCHAR NOT NULL);
  
  
  
            CREATE TABLE [ñ](
  [id-ñ] INTEGER PRIMARY KEY AUTOINCREMENT,
  [mot] VARCHAR NOT NULL,
  [type] VARCHAR NOT NULL);
  
  
  
  CREATE TABLE [Suffixes_Adjectivaux](
  [id_suff_adj] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  [suffixe] VARCHAR NOT NULL);

    CREATE TABLE [Suffixes_Averbiaux](
  [id_suff_adv] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  [suffixe] VARCHAR NOT NULL);
  
    CREATE TABLE [Suffixes_Nominaux](
  [id_suff_nom] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  [suffixe] VARCHAR NOT NULL);
  
      CREATE TABLE [Suffixes_PosPoses](
  [id_suff_posposes] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  [suffixe] VARCHAR NOT NULL);
  
  
      CREATE TABLE [Suffixes_Pronomiaux](
  [id_suff_pronom] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  [suffixe] VARCHAR NOT NULL);
  
  
      CREATE TABLE [Suffixes_VerbauxInterPosition](
  [id_suff_] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  [suffixe] VARCHAR NOT NULL);
  
  
  
  

  
  
